analyzer:
  exclude:
    # Exclude the embedded Flutter SDK and its package tests which are not part
    # of this project's source. The CI should analyze the `app/` package only.
    - flutter/**
    - '**/flutter/**'
    # Exclude IDE / tool scratch directories if present
    - .dart_tool/**
    - build/**

# NOTE: we intentionally don't include `package:flutter_lints/flutter.yaml` here
# because the root workspace isn't a resolvable Dart package (and running
# `flutter pub get` at the repo root isn't required). To enable the Flutter
# recommended lints for the `app/` package, run `flutter pub get` inside
# `app/` and add the include into `app/analysis_options.yaml` (or re-enable
# the line below once package resolution is available).
# include: package:flutter_lints/flutter.yaml
