version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: webqx/mmt-backend:local
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_URL=redis://redis:6379/0
      - VAULT_ADDR=""
      # Add other env as needed; the chart values list keys under deploy/helm/mmt/values.yaml
    depends_on:
      - redis
      - rabbitmq
    restart: unless-stopped

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  web:
    image: nginx:alpine
    volumes:
      - ./app/build/web:/usr/share/nginx/html:ro
      - ./deploy/nginx/local-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: mmt-local
