version: '3.8'

services:
  nextcloud:
    image: nextcloud:apache
    restart: unless-stopped
    environment:
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: changeme
      NEXTCLOUD_TRUSTED_DOMAINS: localhost nextcloud
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/status.php || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        INCLUDE_ML: 0
    image: mmt-backend:local
    restart: unless-stopped
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      REDIS_URL: redis://redis:6379/0
      RATE_LIMIT_PER_MINUTE: 120
      STORE_PHI: "true"
      ENABLE_LOCAL_TRANSCRIPTION: 0
      STORAGE_PROVIDER: nextcloud
      NEXTCLOUD_BASE_URL: http://nextcloud
      NEXTCLOUD_USERNAME: admin
      NEXTCLOUD_PASSWORD: changeme
    depends_on:
      - rabbitmq
      - redis
    ports:
      - "8000:9000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/health/live || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile.web
    image: mmt-frontend:local
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      API_BASE_URL: http://localhost:8000
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend-landing:
    build:
      context: ./frontend-landing
      dockerfile: Dockerfile
    image: mmt-frontend-landing:local
    depends_on:
      - django-whisper
      - nextcloud
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  django-whisper:
    build:
      context: ./medtranscribe_backend
      dockerfile: Dockerfile
    image: django-whisper:local
    restart: unless-stopped
    volumes:
      - ./medtranscribe_backend:/app
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: adminpass
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_DB_ENGINE: sqlite3
      NEXTCLOUD_BASE_URL: http://nextcloud
      NEXTCLOUD_USERNAME: admin
      NEXTCLOUD_PASSWORD: changeme
    depends_on:
      - nextcloud
    ports:
      - "8001:8000"

volumes:
  nextcloud_data:
    driver: local


