version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: openemr
      MYSQL_PASSWORD: openemr
      MYSQL_DATABASE: openemr
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  openemr:
    image: openemr/openemr:latest
    restart: unless-stopped
    environment:
      OE_USER: admin
      OE_PASS: pass
      OE_SITE: default
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASS: root
      OE_INSTALL: '1'
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local
