# Render service manifest (optional)
# If you connect this repo to Render you can use this manifest to configure
# a web service that pulls the backend Docker image from GHCR or builds from
# the repo Dockerfile.

services:
  - type: web_service
    name: mmt-backend
    env: docker
    # image can be overridden in Render UI: ghcr.io/<owner>/mmt-backend:latest
    image: ghcr.io/<owner>/mmt-backend:latest
    plan: free
    region: oregon
    # health check path
    health_check_path: /health
    dockerfile_path: backend/Dockerfile
    # environment variables should be added in the Render dashboard (do not commit secrets)
