groups:
  - name: mmt-backend-reliability
    rules:
      - alert: HighDLQIngressRate
        expr: rate(consumer_dlq_total[5m]) > 0.1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: High DLQ ingress rate
          description: 'Messages are entering DLQ at >0.1/sec for 10m.'
      - alert: ReprocessorPermanentFailures
        expr: increase(reprocessor_permanent_failure_total[15m]) > 0
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: DLQ reprocessor permanent failures detected
          description: 'One or more messages exhausted retries in the last 15m.'
      - alert: ReprocessorNoSuccess
        expr: rate(reprocessor_attempt_total[10m]) > 0 and rate(reprocessor_success_total[10m]) == 0
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: DLQ reprocessor not successfully republishing
          description: 'Attempts occurring but no successes for 15m.'
      - alert: AsyncQueueSaturation
        expr: avg_over_time(async_task_queue_size[5m]) / max(1, ignoring(instance) (max_over_time(async_task_queue_size[5m]))) > 0.9 and avg_over_time(async_task_queue_size[5m]) > 0
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Async submission queue near full
          description: 'Async queue size >90% of historical max for 10m.'
      - alert: CircuitBreakerOpenBurst
        expr: increase(breaker_open_total[10m]) > 0
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Circuit breaker opened
          description: 'At least one breaker open event in last 10m.'
      - alert: PublishFailureRateHigh
        expr: rate(publish_failures_total[5m]) > 0.05 * rate(transcripts_published_total[5m]) and rate(transcripts_published_total[5m]) > 0
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: High publish failure rate
          description: 'Publish failures >5% over 10m.'
  - name: mmt-backend-latency-and-scaling
    rules:
      - alert: HighTranscriptionLatencyP95
        expr: job:mmt_transcription_latency_seconds:p95 > 5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Elevated transcription duration p95
          description: 'p95 transcription duration >5s for 10m.'
      - alert: HighE2ELatencyP95
        expr: job:mmt_e2e_latency_seconds:p95 > 15
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Elevated end-to-end latency p95
          description: 'p95 end-to-end latency >15s for 10m.'
      - alert: PersistentQueueBacklog
        expr: job:mmt_queue_depth:avg1m > 100
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: Queue backlog sustained
          description: 'Average queue depth >100 messages for 15m.'
      - alert: AmbientThroughputDrop
        expr: rate(transcripts_published_total{source="api"}[10m]) < 0.1 and increase(transcripts_published_total{source="api"}[1h]) > 0
        for: 20m
        labels:
          severity: warning
        annotations:
          summary: Ambient publish throughput drop
          description: 'Recent publish rate extremely low vs prior hour baseline.'
      - alert: VaultKeyRefreshFailures
        expr: job:mmt_vault_refresh_failures:rate5m > 0
        for: 10m
        labels:
          severity: warning
        annotations:
            summary: Vault key refresh failures detected
            description: 'Vault key refresh failing over last 10m.'
      - alert: VaultTokenRenewFailures
        expr: job:mmt_vault_token_renew_failures:rate5m > 0
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Vault token renew failures detected
          description: 'Vault token renew failing over last 10m.'
  - name: mmt-backend-red
    rules:
      - alert: HighErrorRate
        expr: sum(rate(api_requests_total{code=~"5.."}[5m])) / sum(rate(api_requests_total[5m])) > 0.05
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: High 5xx error rate
          description: '>5% 5xx responses over 10m.'
      - alert: SlowRequestLatencyP95
        expr: histogram_quantile(0.95, sum by (le) (rate(api_request_duration_seconds_bucket[5m]))) > 0.75
        for: 15m
        labels:
            severity: warning
        annotations:
            summary: Elevated API request latency p95
            description: 'p95 request latency >750ms for 15m.'
      - alert: ExcessInFlightRequests
        expr: avg_over_time(api_in_flight_requests[5m]) > 50
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Sustained high concurrency
          description: 'In-flight requests averaging >50 for 10m.'