[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "ffmpeg", "git", "gcc", "pkg-config"]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.base.txt",
    "echo 'INCLUDE_ML environment variable: $INCLUDE_ML'",
    "if [ \"${INCLUDE_ML:-false}\" = \"true\" ]; then echo 'Installing ML dependencies...' && pip install -r requirements.ml.txt; else echo 'Skipping ML dependencies'; fi"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "python run.py"