apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "mmt.fullname" . }}-dlq-reprocess
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: dlq-reprocessor
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["python", "-m", "dlq_reprocessor"]
              env:
                - name: RABBITMQ_URL
                  value: {{ .Values.rabbitmq.url | quote }}