FROM ghcr.io/cirruslabs/flutter:stable AS build
WORKDIR /app
COPY . .
# Enable faster build by pre-downloading dependencies
RUN flutter pub get && flutter build web --release --base-href /

FROM nginx:alpine
COPY --from=build /app/build/web /usr/share/nginx/html
EXPOSE 80
HEALTHCHECK --interval=30s --timeout=5s --retries=3 CMD wget -q -O /dev/null http://localhost/ || exit 1
