name: mmt
version: 0.3.0
description: Multilingual Medical Transcription Flutter App

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  record: ^4.3.0
  http: ^1.2.0
  audioplayers: ^5.2.0
  path_provider: ^2.1.0
  provider: ^6.0.0
  file_picker: ^6.1.1
  printing: ^5.12.0
  pdf: ^3.10.1
  url_launcher: ^6.2.6
  sentry_flutter: ^8.3.0
  speech_to_text: ^6.6.0
  permission_handler: ^11.0.1
  flutter_appauth: ^6.0.4
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
