name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
      - name: Install deps (including editable backend)
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install -e backend
      - name: Lint (flake8)
        run: flake8 backend
      - name: Type check (mypy)
        run: mypy backend
      - name: Security scan (safety)
        run: safety check -r backend/requirements.txt || true
      - name: Build backend image (for scan)
        run: docker build -f backend/Dockerfile -t mmt-backend:ci . || true
      - name: Trivy image scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'mmt-backend:ci'
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
          ignore-unfixed: true
      - name: Generate SBOM (cyclonedx)
        run: |
          pip install cyclonedx-bom && cyclonedx-bom -r -i backend/requirements.txt -o sbom.xml || true
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.xml
      - name: Tests
        run: pytest -q