name: Deploy Flutter web to GitHub Pages

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Optionally override API base URL for the web build (set this in repository secrets if you have a production API)
      PROD_BASE_URL: ${{ secrets.PROD_BASE_URL || '' }}
      # OpenAI API key for Whisper integration
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            app/.dart_tool
          key: flutter-pub-${{ runner.os }}-${{ hashFiles('app/pubspec.lock') }}
          restore-keys: |
            flutter-pub-${{ runner.os }}-

      - name: Install deps
        working-directory: app
        run: flutter pub get

      - name: Build web (capture log)
        working-directory: app
        run: |
          mkdir -p /tmp/build-logs
          BUILD_CMD="flutter build web --base-href /MMT/"
          if [ -n "${PROD_BASE_URL}" ]; then
            BUILD_CMD="$BUILD_CMD --dart-define=BASE_URL=${PROD_BASE_URL}"
            echo "Using PROD_BASE_URL for build"
          else
            echo "No PROD_BASE_URL set; build will use default BASE_URL (http://localhost:8000)"
          fi
          if [ -n "${OPENAI_API_KEY}" ]; then
            BUILD_CMD="$BUILD_CMD --dart-define=OPENAI_API_KEY=${OPENAI_API_KEY}"
            echo "Using OPENAI_API_KEY for build"
          else
            echo "No OPENAI_API_KEY set; OpenAI Whisper features may be limited"
          fi
          echo "Running: $BUILD_CMD"
          /bin/sh -c "$BUILD_CMD" 2>&1 | tee /tmp/build-logs/flutter_build.log

      - name: List build output
        run: |
          ls -la app/build/web || true
          du -sh app/build/web || true

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flutter-build-artifacts
          path: |
            app/build/web
            /tmp/build-logs/flutter_build.log

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: app/build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        env:
          ACTIONS_DEPLOY_PAGES_DISABLE_FRAMEWORKS: true
