name: Build and deploy Flutter web to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build Flutter web and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          # Request latest Flutter release so the bundled Dart SDK satisfies newer package SDK constraints
          flutter-version: 'latest'
          channel: stable

      - name: Show Flutter & Dart versions
        run: |
          flutter --version || true
          dart --version || true

      - name: Cache Pub packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.cache/flutter
          key: ${{ runner.os }}-flutter-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-pub-

      - name: Install dependencies (verbose)
        working-directory: app
        run: |
          echo 'Resolving Flutter/Dart dependencies (verbose)'
          flutter pub get --verbose || (echo 'flutter pub get failed'; cat pubspec.yaml; exit 1)
          echo 'pubspec.lock contents:'
          cat pubspec.lock || true

      - name: Analyze Dart/Flutter code
        working-directory: app
        run: |
          echo "Running flutter analyze (will fail the job if issues found)"
          flutter analyze

      - name: Run Flutter tests
        working-directory: app
        run: |
          echo "Running flutter tests"
          flutter test --no-pub --coverage || true

      - name: Build Flutter web
        working-directory: app
        env:
          PUBLIC_BACKEND_URL: ${{ secrets.PUBLIC_BACKEND_URL }}
        run: |
          if [ -n "$PUBLIC_BACKEND_URL" ]; then
            echo "Building with PUBLIC_BACKEND_URL=$PUBLIC_BACKEND_URL"
            flutter build web --base-href /MMT/ --dart-define=BASE_URL=$PUBLIC_BACKEND_URL
          else
            echo "Building with default BASE_URL (localhost)"
            flutter build web --base-href /MMT/
          fi

      - name: Create .nojekyll (prevent GitHub Pages ignoring files)
        run: |
          mkdir -p app/build/web
          touch app/build/web/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/build/web
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
