name: Deploy Flutter web to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.6'
          channel: stable

      - name: Install deps
        working-directory: app
        run: flutter pub get

      - name: Build web (capture log)
        working-directory: app
        run: |
          mkdir -p /tmp/build-logs
          flutter build web --base-href /MMT/ 2>&1 | tee /tmp/build-logs/flutter_build.log

      - name: List build output
        run: |
          ls -la app/build/web || true
          du -sh app/build/web || true

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flutter-build-artifacts
          path: |
            app/build/web
            /tmp/build-logs/flutter_build.log

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/build/web
          publish_branch: gh-pages
