name: Build & Deploy Flutter Web to GitHub Pages
on:
  push:
    branches: [ main, feat/ci-flutter ]

permissions:
  contents: read
  pages: write
  id-token: write
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install app deps
        run: |
          cd app
          flutter pub get

      - name: Build Flutter web
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: |
          cd app
          if [ -z "$BACKEND_URL" ]; then echo "WARNING: BACKEND_URL secret not set — build will use default BASE_URL"; fi
          flutter build web --release --dart-define=BASE_URL=${BACKEND_URL}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/build/web
