name: Deploy Flutter web to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      # Optionally override API base URL for the web build (set this in repository secrets if you have a production API)
      PROD_BASE_URL: ${{ secrets.PROD_BASE_URL || '' }}
      # OpenAI API key for Whisper integration
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: stable

      - name: Install deps
        working-directory: app
        run: flutter pub get

      - name: Build web (capture log)
        working-directory: app
        run: |
          mkdir -p /tmp/build-logs
          BUILD_CMD="flutter build web --base-href /MMT/"
          if [ -n "${PROD_BASE_URL}" ]; then
            BUILD_CMD="$BUILD_CMD --dart-define=BASE_URL=${PROD_BASE_URL}"
            echo "Using PROD_BASE_URL for build"
          else
            echo "No PROD_BASE_URL set; build will use default BASE_URL (http://localhost:8000)"
          fi
          if [ -n "${OPENAI_API_KEY}" ]; then
            BUILD_CMD="$BUILD_CMD --dart-define=OPENAI_API_KEY=${OPENAI_API_KEY}"
            echo "Using OPENAI_API_KEY for build"
          else
            echo "No OPENAI_API_KEY set; OpenAI Whisper features may be limited"
          fi
          echo "Running: $BUILD_CMD"
          /bin/sh -c "$BUILD_CMD" 2>&1 | tee /tmp/build-logs/flutter_build.log

      - name: List build output
        run: |
          ls -la app/build/web || true
          du -sh app/build/web || true

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flutter-build-artifacts
          path: |
            app/build/web
            /tmp/build-logs/flutter_build.log

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/build/web
          publish_branch: gh-pages
