name: firebase-web

on:
  push:
    branches: [ main ]
    paths:
      - 'app/lib/**'
      - 'app/web/**'
      - 'app/pubspec.yaml'
      - '.github/workflows/firebase_web.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Flutter pub get
        working-directory: app
        run: flutter pub get
      - name: Build web
        working-directory: app
        run: flutter build web --release --base-href "/"
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
