name: Mobile CI

on:
  pull_request:
    paths:
      - 'app/**'
  push:
    branches: [ main ]
    paths:
      - 'app/**'

jobs:
  flutter-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Pub get
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test --no-pub --coverage
      - name: Build APK (release)
        run: flutter build apk --release --dart-define=BASE_URL=https://example --dart-define=KEYCLOAK_ISSUER=https://keycloak/realms/mmt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/app/outputs/flutter-apk/app-release.apk
