name: performance

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"  # nightly

jobs:
  locust-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Start API
        env:
          ENV: dev
        run: |
          nohup python -m uvicorn backend.main:app --port 8000 &
          for i in $(seq 1 30); do curl -sf localhost:8000/health/live && break || sleep 1; done
      - name: Run Locust headless
        env:
          LOCUST_HOST: http://localhost:8000
        run: |
          locust -f backend/perf/locustfile.py --headless -u 15 -r 5 -t 45s --only-summary --exit-code-on-error 1
      - name: Archive Locust HTML (optional)
        if: always()
        run: |
          echo "No HTML report generated (headless only)."